lab2: sort.c File Reference
sort.c File Reference
#include <stdio.h>
#include "sort.h"
#include "print_arrays.h"
Functions
void sort (int a[], int length)
int myrand (int max)
int myrands (int max, int count)
Function Documentation
int myrand (int max)
Generates a (suedo) random integer between 0 and max inclusive
Parameters
max Maximum value for generated random number
Returns
num Random number that has been generated
Referenced by myrands().
int myrands (int max, int count)
Generates an array of (suedo) random integers between 0 and max inclusive
Parameters
max Maximum value for generated random number
count The number of random numbers to generate
Returns
a Aan array of random number that has been generated
References myrand().
void sort (int a[], int length)
file sort.c
Author
Kaitlyn DaSilva
Parameters
arr[] an array of integers
length the length of arr[]
Function which sorts an array of ints into ascending order.
Referenced by main().